" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" You can also specify a different font, overriding the default font
"if has('gui_gtk2')
"  set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
"else
"  set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
"endif

" If you want to run gvim with a dark background, try using a different
" colorscheme or running 'gvim -reverse'.
" http://www.cs.cmu.edu/~maverick/VimColorSchemeTest/ has examples and
" downloads for the colorschemes on vim.org

" Source a global configuration file if available
"set bg=light

"colorscheme torte
"colorscheme koehler
"colorscheme eclipse
"set bg=dark
"colorscheme desert
"set bg=dark
"colorscheme desert_mindentropy
"set bg=light
"colorscheme mindentropy
"colorscheme Tomorrow-Night-Blue
"set bg=dark
"colorscheme jellybeans_mindentropy
"colorscheme asmanian2
"set termguicolors
"colorscheme desert
"colorscheme solarized
"let ayucolor="light"
"colorscheme ayu
"colorscheme slate
"set bg=light
"set bg=dark

if filereadable("/etc/vim/gvimrc.local")
  source /etc/vim/gvimrc.local
endif

set guifont=0xProto\ 17
"set guifont=Geist\ Mono\ Medium\ 22
"set guifont=Agave\ 23
"set guifont=Fira\ Code\ weight=453\ 19
"set guifont=Inconsolata\ Medium\ 23
"set guifont=Anonymous\ Pro\ 20
"set guifont=Bitstream\ Vera\ Sans\ Mono\ 23
"set guifont=Ubuntu\ Mono\ 28
"set guifont=Source\ Code\ Pro\ Medium\ 24
"set guifont=Fantasque\ Sans\ Mono\ 24
"set guifont=Hermit\ 22
"set guifont=IBM\ Plex\ Mono\ weight=474\ 19
"set guifont=PT\ Mono\ 19
"set guifont=0xProto\ 21
set foldmethod=syntax
set guicursor=a:blinkon0
set guioptions-=m "Remove menubar
set guioptions-=T "Remove toolbar
set guioptions+=k
set guicursor=a:blinkon300
set guicursor=a:blinkoff300
set vb t_vb=

"set cul
"set cuc
