" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" You can also specify a different font, overriding the default font
"if has('gui_gtk2')
"  set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
"else
"  set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
"endif

" If you want to run gvim with a dark background, try using a different
" colorscheme or running 'gvim -reverse'.
" http://www.cs.cmu.edu/~maverick/VimColorSchemeTest/ has examples and
" downloads for the colorschemes on vim.org

" Source a global configuration file if available
"set bg=light

"colorscheme torte
"colorscheme koehler
colorscheme eclipse
"colorscheme desert

"colorscheme asmanian2
"set bg=dark
set bg=light

if filereadable("/etc/vim/gvimrc.local")
  source /etc/vim/gvimrc.local
endif

set guifont=Ubuntu\ Mono\ 21.5
set guicursor=a:blinkon0
set guioptions-=m "Remove menubar
set guioptions-=T "Remove toolbar
set guicursor=a:blinkon300
set guicursor=a:blinkoff300

"set cul
"set cuc
