set nu
set showcmd
set showmatch
set tabstop=4
set hlsearch
set ai
set mouse=a
set autowriteall
set incsearch
set hidden
syntax on

set cst
set guioptions-=m "Remove menu bar
set guioptions-=T "Remove tool bar

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'ervandew/supertab'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'godlygeek/tabular'
Plugin 'majutsushi/tagbar'
Plugin 'altercation/vim-colors-solarized'
Plugin 'morhetz/gruvbox'
Plugin 'tpope/vim-fugitive'

call vundle#end()

"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

nnoremap <F2> :buffers<CR>:buffer<SPACE>
nnoremap <F3> :NERDTreeToggle<CR>
nnoremap <C-n> :NERDTreeMirror<CR>:NERDTreeFocus<CR>

nnoremap <F4> :set nu! rnu!<CR>
"nnoremap <F4> :!make clean<CR>
"nnoremap <F5> :!make<CR>

nnoremap <F7> :cs reset<CR>

nnoremap <F9> :vnew<CR>:read !svn diff<CR>:set syntax=diff buftype=nofile<CR>gg

nnoremap <F11> :cscope<SPACE>add<SPACE>cscope.out<CR>
nnoremap <F12> :cs<SPACE>reset<CR>

nnoremap ,cd :cd %:p:h<CR>:pwd<CR>

nmap <F8> :TagbarToggle<CR>

nnoremap <C-S-t> :tabnew<CR>
nnoremap <S-h> gT
nnoremap <S-l> gt

nnoremap <S-F1> 1gt
nnoremap <S-F2> 2gt
nnoremap <S-F3> 3gt
nnoremap <S-F4> 4gt
nnoremap <S-F5> 5gt
nnoremap <S-F6> 6gt
nnoremap <S-F7> 7gt
nnoremap <S-F8> 8gt
nnoremap <S-F9> 9gt


set laststatus=1
"set mousehide
set autowriteall
set noswapfile
"set mousefocus
let NERDTreeWinPos="right"
let NERDTreeQuitOnOpen=1
let g:autosave=1
let g:airline_theme='cobalt2'

augroup filetypedetect
	au! BufRead,BufNewFile *.m,*.oct set filetype=octave
augroup END

"augroup numbertoggle
"  autocmd!
"  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
"  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
"augroup END
